"""add modified_at Second TRY - 00

Revision ID: 1d0badd08260
Revises: 6e3de3ffdc10
Create Date: 2023-10-23 20:11:57.293900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d0badd08260"
down_revision: Union[str, None] = "6e3de3ffdc10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("note", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("note", "description", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("note", "description", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("note", "name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
