"""many setting player data_01

Revision ID: 3135bdf5e17c
Revises: 6be1d0ae842e
Create Date: 2023-10-25 19:28:09.370126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3135bdf5e17c'
down_revision: Union[str, None] = '6be1d0ae842e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gameinfo', 'start_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('player', sa.Column('total_buyin', sa.Float(), nullable=False))
    op.add_column('player', sa.Column('total_out', sa.Float(), nullable=False))
    op.add_column('player', sa.Column('net_score', sa.Float(), nullable=True))
    op.add_column('player', sa.Column('no_of_games', sa.Integer(), nullable=False))
    op.add_column('player', sa.Column('get_bbozzi_ratio', sa.Float(), nullable=True))
    op.add_column('player', sa.Column('set_bbozzi_ratio', sa.Float(), nullable=True))
    op.drop_column('player', 'setbbozziratio')
    op.drop_column('player', 'totalout')
    op.drop_column('player', 'totalbuyin')
    op.drop_column('player', 'noofgames')
    op.drop_column('player', 'getbbozziratio')
    op.drop_column('player', 'netscore')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('netscore', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('player', sa.Column('getbbozziratio', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('player', sa.Column('noofgames', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('player', sa.Column('totalbuyin', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('player', sa.Column('totalout', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('player', sa.Column('setbbozziratio', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('player', 'set_bbozzi_ratio')
    op.drop_column('player', 'get_bbozzi_ratio')
    op.drop_column('player', 'no_of_games')
    op.drop_column('player', 'net_score')
    op.drop_column('player', 'total_out')
    op.drop_column('player', 'total_buyin')
    op.alter_column('gameinfo', 'start_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
