"""try default 03

Revision ID: 7ceff28884ac
Revises: e4925068d03f
Create Date: 2023-10-23 16:43:29.410447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ceff28884ac"
down_revision: Union[str, None] = "e4925068d03f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "gameinfo", "netPlayer", existing_type=sa.Integer(), server_default="0"
    )
    op.alter_column(
        "gameinfo", "netBuyin", existing_type=sa.Integer(), server_default="0"
    )
    op.alter_column(
        "gameinfo", "netGamefee", existing_type=sa.Integer(), server_default="0"
    )
    op.alter_column(
        "gameinfo", "netBbozzi", existing_type=sa.Integer(), server_default="0"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
