"""add modified_at Second TRY - 8

Revision ID: 91678e531059
Revises: 95a9bd2bd5c1
Create Date: 2023-10-25 10:41:13.854832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91678e531059'
down_revision: Union[str, None] = '95a9bd2bd5c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('modified_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'modified_at')
    # ### end Alembic commands ###
