"""Adjust minor change on gameinfo

Revision ID: 9b22d36a2b98
Revises: 26b88952d290
Create Date: 2023-10-23 16:02:52.414278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9b22d36a2b98"
down_revision: Union[str, None] = "26b88952d290"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "gameinfo", "finish", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "gameinfo", "playtimemin", existing_type=sa.INTEGER(), nullable=True
    )

    # 기본값 추가
    op.alter_column(
        "gameinfo", "netplayer", existing_type=sa.Integer(), server_default="0"
    )
    op.alter_column(
        "gameinfo", "netbuyin", existing_type=sa.Float(), server_default="0"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "gameinfo", "playtimemin", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "gameinfo", "finish", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###
