"""playtimeMin -> playtime_min

Revision ID: cad171cdb074
Revises: 9f918f578dc1
Create Date: 2023-10-23 16:12:18.605513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad171cdb074'
down_revision: Union[str, None] = '9f918f578dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameinfo', sa.Column('playtime_min', sa.Integer(), nullable=True))
    op.drop_column('gameinfo', 'playtimeMin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameinfo', sa.Column('playtimeMin', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('gameinfo', 'playtime_min')
    # ### end Alembic commands ###
