"""add modified_at Second TRY - 04

Revision ID: 34a533df5135
Revises: f7094684ecb1
Create Date: 2023-10-23 20:33:09.831364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a533df5135'
down_revision: Union[str, None] = 'f7094684ecb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('test_timestamp01_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'test_timestamp01_at')
    # ### end Alembic commands ###
