"""many setting gameinfo data_02

Revision ID: 6be1d0ae842e
Revises: 8530e6aae58b
Create Date: 2023-10-25 15:21:05.057939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6be1d0ae842e'
down_revision: Union[str, None] = '8530e6aae58b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameinfo', sa.Column('net_player', sa.Integer(), nullable=False))
    op.add_column('gameinfo', sa.Column('net_buyin', sa.Float(), nullable=False))
    op.add_column('gameinfo', sa.Column('net_gamefee', sa.Float(), nullable=False))
    op.add_column('gameinfo', sa.Column('net_bbozzi', sa.Float(), nullable=False))
    op.add_column('gameinfo', sa.Column('start_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('gameinfo', sa.Column('finish_at', sa.DateTime(), nullable=True))
    op.add_column('gameinfo', sa.Column('playtime_min', sa.Integer(), nullable=True))
    op.drop_column('gameinfo', 'netBuyin')
    op.drop_column('gameinfo', 'playtimeMin')
    op.drop_column('gameinfo', 'netPlayer')
    op.drop_column('gameinfo', 'netGamefee')
    op.drop_column('gameinfo', 'startAt')
    op.drop_column('gameinfo', 'finishAt')
    op.drop_column('gameinfo', 'netBbozzi')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameinfo', sa.Column('netBbozzi', postgresql.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('gameinfo', sa.Column('finishAt', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('gameinfo', sa.Column('startAt', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('gameinfo', sa.Column('netGamefee', postgresql.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('gameinfo', sa.Column('netPlayer', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('gameinfo', sa.Column('playtimeMin', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('gameinfo', sa.Column('netBuyin', postgresql.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.drop_column('gameinfo', 'playtime_min')
    op.drop_column('gameinfo', 'finish_at')
    op.drop_column('gameinfo', 'start_at')
    op.drop_column('gameinfo', 'net_bbozzi')
    op.drop_column('gameinfo', 'net_gamefee')
    op.drop_column('gameinfo', 'net_buyin')
    op.drop_column('gameinfo', 'net_player')
    # ### end Alembic commands ###
