"""playtimemin -> playtimeMin

Revision ID: 9f918f578dc1
Revises: 9b22d36a2b98
Create Date: 2023-10-23 16:10:38.807764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f918f578dc1'
down_revision: Union[str, None] = '9b22d36a2b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameinfo', sa.Column('playtimeMin', sa.Integer(), nullable=True))
    op.drop_column('gameinfo', 'playtimemin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gameinfo', sa.Column('playtimemin', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('gameinfo', 'playtimeMin')
    # ### end Alembic commands ###
