"""try default 03

Revision ID: e4925068d03f
Revises: a7f4687c4960
Create Date: 2023-10-23 16:39:56.854925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e4925068d03f"
down_revision: Union[str, None] = "a7f4687c4960"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gameinfo",
        sa.Column("netPlayer", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "gameinfo",
        sa.Column("netBuyin", sa.Float(), server_default="0", nullable=False),
    )
    op.add_column(
        "gameinfo",
        sa.Column("netGamefee", sa.Float(), server_default="0", nullable=False),
    )
    op.add_column(
        "gameinfo",
        sa.Column("netBbozzi", sa.Float(), server_default="0", nullable=False),
    )
    op.add_column("gameinfo", sa.Column("startAt", sa.DateTime(), nullable=False))
    op.add_column("gameinfo", sa.Column("finishAt", sa.DateTime(), nullable=True))
    op.drop_column("gameinfo", "netgamefee")
    op.drop_column("gameinfo", "netbuyin")
    op.drop_column("gameinfo", "netplayer")
    op.drop_column("gameinfo", "netbbozzi")
    op.drop_column("gameinfo", "finish")
    op.drop_column("gameinfo", "start")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gameinfo",
        sa.Column("start", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "gameinfo",
        sa.Column("finish", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "gameinfo",
        sa.Column(
            "netbbozzi",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "gameinfo",
        sa.Column("netplayer", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "gameinfo",
        sa.Column(
            "netbuyin",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "gameinfo",
        sa.Column(
            "netgamefee",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("gameinfo", "finishAt")
    op.drop_column("gameinfo", "startAt")
    op.drop_column("gameinfo", "netBbozzi")
    op.drop_column("gameinfo", "netGamefee")
    op.drop_column("gameinfo", "netBuyin")
    op.drop_column("gameinfo", "netPlayer")
    # ### end Alembic commands ###
