"""add modified_at Second TRY - 02

Revision ID: f7094684ecb1
Revises: 1d0badd08260
Create Date: 2023-10-23 20:20:15.985322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f7094684ecb1"
down_revision: Union[str, None] = "1d0badd08260"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "note",
        sa.Column(
            "modified_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )
    op.alter_column("note", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("note", "description", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("note", "description", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("note", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("note", "modified_at")
    # ### end Alembic commands ###
